apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: production-web
  name: production-web
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: production-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: production-web
    spec:
      containers:
      - args:
        - exec
        - puma
        command:
        - bundle
        envFrom:
          - configMapRef:
              name: production-sidekiq-config-ctbs
        image: gcr.io/tecorb-infra/github.com/tecorb/platform@sha256:5b9039c1ccf485eder9e3a7c0943c3a3400md32a1nde93p0394054l1b3ld4m1p
        imagePullPolicy: IfNotPresent
        name: platform-sha256-1
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
